# Advanced Indexing in NumPy

NumPy supports two main advanced indexing modes:
1. **Integer (fancy) indexing**
2. **Boolean (mask) indexing**

These allow selecting arbitrary elements — not just contiguous slices.


In [23]:
import numpy as np

X = np.arange(12).reshape(3, 4)
rows = np.array([0, 2])
cols = np.array([1, 3])

print("X")
print(X)
print("\nX[rows, cols]")
print(X[rows, cols])


X
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

X[rows, cols]
[ 1 11]


### index cross helper

In [24]:
print("Indices")
print(np.ix_(rows, cols))

print("Submatrix")
X[np.ix_(rows, cols)]

Indices
(array([[0],
       [2]]), array([[1, 3]]))
Submatrix


array([[ 1,  3],
       [ 9, 11]])

## Boolean Mask Indexing - Masking

Masking lets you **select elements** of an array using a Boolean array of the same
shape — like a filter.

In [25]:
X = np.arange(12).reshape(3, 4)
mask = X % 2 == 0     # True where even

print("X")
print(X)
print("\nmask")
print(mask)
print("\nX[mask]")
print(X[mask])



X
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

mask
[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]

X[mask]
[ 0  2  4  6  8 10]


In [27]:
print("Rows with sum > 10")
print(X[X.sum(axis=1) > 10])

Rows with sum > 10
[[ 4  5  6  7]
 [ 8  9 10 11]]


In [26]:
# Use & (and), | (or), ~ (not), with parentheses
print("Elements between 2 and 9")
print(X[(X > 2) & (X < 9)])

Elements between 2 and 9
[3 4 5 6 7 8]


#### Masking in 2D arrays

In [28]:
row_mask = np.array([True, False, True])
print("Rows with True in row_mask")
print(X[row_mask, :])


Rows with True in row_mask
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [29]:
# NumPy does not support multi-axis Boolean masks in one shot (e.g. a 2D mask to
# select along rows and columns simultaneously).
# You need to apply the masks sequentially.

row_mask = X.mean(axis=1) > 4    # select rows whose mean > 4
col_mask = X.max(axis=0) < 10    # select columns whose max < 10
X[row_mask][:, col_mask]

print("Rows with mean > 4 and columns with max < 10")
print(X[row_mask][:, col_mask])

Rows with mean > 4 and columns with max < 10
[[4 5]
 [8 9]]


### np.where

In [30]:
print("Replace odd numbers with -1")
np.where(X % 2 == 0, X, -1)

Replace odd numbers with -1


array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1]])

In [31]:
# get the indices of the elements that are even
print("Indices of even elements")
print(np.where(X % 2 == 0))


Indices of even elements
(array([0, 0, 1, 1, 2, 2]), array([0, 2, 0, 2, 0, 2]))
